name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [ '2.2.402', '3.0.100' ]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: build ${{ matrix.dotnet }}
      run: dotnet build
    - name: test ${{ matrix.dotnet }}
      run: dotnet test
